export const title = '世足球星誰稱王 - 報導者 The Reporter'
export const ogDescription = '梅西、C羅、席丹、羅納度⋯本世紀哪些球星在世足有最多成就？排完後告訴你！'
export const ogImage = 'https://storage.googleapis.com/twreporter-infographics/21centry-football-players-ranking-gcs/static/og-new.png'
export const ogUrl = 'https://www.twreporter.org/i/21centry-football-players-ranking-gcs'
export const fbAppId = '1296686743779808'
